# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sopt_7th_iOS_seminar' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sopt_7th_iOS_seminar
	pod 'Alamofire'
	pod 'AlamofireObjectMapper'
	pod 'ObjectMapper'
	pod 'Kingfisher'
end
